In [1]:
import pandas as pd

# Dataframe from python dictionary

In [13]:

data_dictionary = {
    'Name': ['A', 'Gita', 'Hari' ,'C','D','E','F'],
    'Age': [10, 25, 20 ,30,40,50,60],
    'Address' : ['Pokhara','das','sad','sada','sadsad','sdsd','sadsasd']
}
df_dict = pd.DataFrame(data_dictionary)
df_dict

   Name  Age  Address
0     A   10  Pokhara
1  Gita   25      das
2  Hari   20      sad
3     C   30     sada
4     D   40   sadsad
5     E   50     sdsd
6     F   60  sadsasd

In [14]:
data_dictionary_list = [{'Name' : "Sandy" , 'Age' : 20 , "Address" : 'Syangja'},
                   {'Name' : "B" , 'Age' : 20 , "Address" : 'Syangja'},
                   {'Name' : "C" , 'Age' : 22 , "Address" : 'Pokhara'},
                   {'Name' : "C" , 'Age' : 24 , "Address" : 'Bakthapur'},
                   {'Name' : "D" , 'Age' : 26 , "Address" : 'Kathmandu'},
                   {'Name' : "E" , 'Age' : 28 , "Address" : 'Khahare'},
                   {'Name' : "E" , 'Age' : 21 , "Address" : 'Palpa'},
                   ]
data_dict_list = pd.DataFrame(data_dictionary_list)
data_dict_list

    Name  Age    Address
0  Sandy   20    Syangja
1      B   20    Syangja
2      C   22    Pokhara
3      C   24  Bakthapur
4      D   26  Kathmandu
5      E   28    Khahare
6      E   21      Palpa

In [11]:
data_tuple = (
    ('Apple', 25, 'Kathmandu'),
    ('Ball', 30, 'Bhaktapur'),
    ('Cat', 35, 'Nepal'),
    ('Dog' , 40 , 'India'),
    ('Egg' , 50 , 'France'),
    ('Fish' , 55,'USA'),
    ('Gun' , 40,'Finland')
)
df_tuple = pd.DataFrame(data_tuple, columns=['Name', 'Age', 'Address'])
df_tuple

    Name  Age    Address
0  Apple   25  Kathmandu
1   Ball   30  Bhaktapur
2    Cat   35      Nepal
3    Dog   40      India
4    Egg   50     France
5   Fish   55        USA
6    Gun   40    Finland

In [9]:
data_list_list = [["Helo", 20 , 'Bhaktapur'],
                  ["Good", 40,"Syangja"],
                  ["Good_Bye", 60,"Pokhara"],
                  ["New", 22 , 'Bhaktapur'],
                  ["Say", 44,"Syangja"],
                  ["_Bye", 62,"Pokhara"],
                  ["Man", 41,"Syangja"],
                  ]

df_list_list = pd.DataFrame(data_list_list, columns=['Name', 'Age' , 'Address'])
df_list_list

       Name  Age    Address
0      Helo   20  Bhaktapur
1      Good   40    Syangja
2  Good_Bye   60    Pokhara
3       New   22  Bhaktapur
4       Say   44    Syangja
5      _Bye   62    Pokhara
6       Man   41    Syangja

<!-- Data CSV Read -->

In [97]:
# df_weather = pd.read_csv('Data/weather_data.csv')
# df_weather => Throws Error
# Task One
import csv as csv
data_file = open('Data/weather_data.csv' , 'r')
csv_file = csv.reader(data_file)
list_data = list(csv_file)
df_weather = pd.DataFrame(list_data[3:] , columns=list_data[2])
df_weather
# print(df)

          day    temperature     windspeed     event
0    1/1/2017             32             6      Rain
1    1/4/2017  not available             9     Sunny
2    1/5/2017             -1  not measured      Snow
3    1/6/2017  not available             7  no event
4    1/7/2017             32  not measured      Rain
5    1/8/2017  not available  not measured     Sunny
6    1/9/2017  not available  not measured  no event
7   1/10/2017             34             8    Cloudy
8   1/11/2017             -4            -1      Snow
9   1/12/2017             26            12     Sunny
10  1/13/2017             12            12     Rainy
11  1/11/2017             -1            12      Snow
12  1/14/2017             40            -1     Sunny

In [60]:
# Advance Try
file_path = "Data/imports-85.data"
import_columns = ['symboling', 'normalized_losses', 'make', 'fuel_type', 'aspiration', 'num_of_doors',
          'body_style', 'drive_wheels', 'engine_location', 'wheel_base', 'length', 'width', 
           'height', 'curb_weight', 'engine_type', 'num_of_cylinders', 'engine_size', 'fuel_system',
          'bore', 'stroke', 'compression', 'horsepower', 'peak_rpm', 'city_mpg', 'highway_mpg', 
           'price']
# print(import_columns)

from csv import reader
file_path = "Data/imports-85.data"

csv_ = open(file_path, "r") 
    
csv_reader = csv.reader(csv_)
pd.DataFrame(csv_reader , columns=import_columns)

# csv_.close()

,symboling,normalized_losses,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.60,...,130,mpfi,3.47,2.68,9.00,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.60,...,130,mpfi,3.47,2.68,9.00,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.50,...,152,mpfi,2.68,3.47,9.00,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.80,...,109,mpfi,3.19,3.40,10.00,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.40,...,136,mpfi,3.19,3.40,8.00,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.10,...,141,mpfi,3.78,3.15,9.50,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.10,...,141,mpfi,3.78,3.15,8.70,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.10,...,173,mpfi,3.58,2.87,8.80,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.10,...,145,idi,3.01,3.40,23.00,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.10,...,141,mpfi,3.78,3.15,9.50,114,5400,19,25,22625

In [100]:
# Task 2
file_path = 'Data/imports-85.data'
file_open = open(file_path , 'r')
csv_data = csv.reader(file_open)
list_data_  = list(csv_data)
# print(list_data_)
pd.DataFrame(list_data_ , columns=import_columns)

[['3', '?', 'alfa-romero', 'gas', 'std', 'two', 'convertible', 'rwd', 'front', '88.60', '168.80', '64.10', '48.80', '2548', 'dohc', 'four', '130', 'mpfi', '3.47', '2.68', '9.00', '111', '5000', '21', '27', '13495'], ['3', '?', 'alfa-romero', 'gas', 'std', 'two', 'convertible', 'rwd', 'front', '88.60', '168.80', '64.10', '48.80', '2548', 'dohc', 'four', '130', 'mpfi', '3.47', '2.68', '9.00', '111', '5000', '21', '27', '16500'], ['1', '?', 'alfa-romero', 'gas', 'std', 'two', 'hatchback', 'rwd', 'front', '94.50', '171.20', '65.50', '52.40', '2823', 'ohcv', 'six', '152', 'mpfi', '2.68', '3.47', '9.00', '154', '5000', '19', '26', '16500'], ['2', '164', 'audi', 'gas', 'std', 'four', 'sedan', 'fwd', 'front', '99.80', '176.60', '66.20', '54.30', '2337', 'ohc', 'four', '109', 'mpfi', '3.19', '3.40', '10.00', '102', '5500', '24', '30', '13950'], ['2', '164', 'audi', 'gas', 'std', 'four', 'sedan', '4wd', 'front', '99.40', '176.60', '66.40', '54.30', '2824', 'ohc', 'five', '136', 'mpfi', '3.19', '3.40', '8.00', '115', '5500', '18', '22', '17450'], ['2', '?', 'audi', 'gas', 'std', 'two', 'sedan', 'fwd', 'front', '99.80', '177.30', '66.30', '53.10', '2507', 'ohc', 'five', '136', 'mpfi', '3.19', '3.40', '8.50', '110', '5500', '19', '25', '15250'], ['1', '158', 'audi', 'gas', 'std', 'four', 'sedan', 'fwd', 'front', '105.80', '192.70', '71.40', '55.70', '2844', 'ohc', 'five', '136', 'mpfi', '3.19', '3.40', '8.50', '110', '5500', '19', '25', '17710'], ['1', '?', 'audi', 'gas', 'std', 'four', 'wagon', 'fwd', 'front', '105.80', '192.70', '71.40', '55.70', '2954', 'ohc', 'five', '136', 'mpfi', '3.19', '3.40', '8.50', '110', '5500', '19', '25', '18920'], ['1', '158', 'audi', 'gas', 'turbo', 'four', 'sedan', 'fwd', 'front', '105.80', '192.70', '71.40', '55.90', '3086', 'ohc', 'five', '131', 'mpfi', '3.13', '3.40', '8.30', '140', '5500', '17', '20', '23875'], ['0', '?', 'audi', 'gas', 'turbo', 'two', 'hatchback', '4wd', 'front', '99.50', '178.20', '67.90', '52.00', '3053', 'ohc', 'five', '131', 'mpfi', '3.13', '3.40', '7.00', '160', '5500', '16', '22', '?'], ['2', '192', 'bmw', 'gas', 'std', 'two', 'sedan', 'rwd', 'front', '101.20', '176.80', '64.80', '54.30', '2395', 'ohc', 'four', '108', 'mpfi', '3.50', '2.80', '8.80', '101', '5800', '23', '29', '16430'], ['0', '192', 'bmw', 'gas', 'std', 'four', 'sedan', 'rwd', 'front', '101.20', '176.80', '64.80', '54.30', '2395', 'ohc', 'four', '108', 'mpfi', '3.50', '2.80', '8.80', '101', '5800', '23', '29', '16925'], ['0', '188', 'bmw', 'gas', 'std', 'two', 'sedan', 'rwd', 'front', '101.20', '176.80', '64.80', '54.30', '2710', 'ohc', 'six', '164', 'mpfi', '3.31', '3.19', '9.00', '121', '4250', '21', '28', '20970'], ['0', '188', 'bmw', 'gas', 'std', 'four', 'sedan', 'rwd', 'front', '101.20', '176.80', '64.80', '54.30', '2765', 'ohc', 'six', '164', 'mpfi', '3.31', '3.19', '9.00', '121', '4250', '21', '28', '21105'], ['1', '?', 'bmw', 'gas', 'std', 'four', 'sedan', 'rwd', 'front', '103.50', '189.00', '66.90', '55.70', '3055', 'ohc', 'six', '164', 'mpfi', '3.31', '3.19', '9.00', '121', '4250', '20', '25', '24565'], ['0', '?', 'bmw', 'gas', 'std', 'four', 'sedan', 'rwd', 'front', '103.50', '189.00', '66.90', '55.70', '3230', 'ohc', 'six', '209', 'mpfi', '3.62', '3.39', '8.00', '182', '5400', '16', '22', '30760'], ['0', '?', 'bmw', 'gas', 'std', 'two', 'sedan', 'rwd', 'front', '103.50', '193.80', '67.90', '53.70', '3380', 'ohc', 'six', '209', 'mpfi', '3.62', '3.39', '8.00', '182', '5400', '16', '22', '41315'], ['0', '?', 'bmw', 'gas', 'std', 'four', 'sedan', 'rwd', 'front', '110.00', '197.00', '70.90', '56.30', '3505', 'ohc', 'six', '209', 'mpfi', '3.62', '3.39', '8.00', '182', '5400', '15', '20', '36880'], ['2', '121', 'chevrolet', 'gas', 'std', 'two', 'hatchback', 'fwd', 'front', '88.40', '141.10', '60.30', '53.20', '1488', 'l', 'three', '61', '2bbl', '2.91', '3.03', '9.50', '48', '5100', '47', '53', '5151'], ['1', '98', 'chevrolet', 'gas', 'std', 'two', 'hatchback', 'fwd', 'front', '94.50', '155.90', '63.60', '52.00', '1874', 'ohc', 'four', '90', '2bbl', '3.03', '3.11', '9.60', '70', '5400', '38', '43', '6295'], ['0', '81', 'chevrolet', 'gas', 'std', 'four', 'sedan', 'fwd', 'front', '94.50', '158.80', '63.60', '52.00', '1909', 'ohc', 'four', '90', '2bbl', '3.03', '3.11', '9.60', '70', '5400', '38', '43', '6575'], ['1', '118', 'dodge', 'gas', 'std', 'two', 'hatchback', 'fwd', 'front', '93.70', '157.30', '63.80', '50.80', '1876', 'ohc', 'four', '90', '2bbl', '2.97', '3.23', '9.41', '68', '5500', '37', '41', '5572'], ['1', '118', 'dodge', 'gas', 'std', 'two', 'hatchback', 'fwd', 'front', '93.70', '157.30', '63.80', '50.80', '1876', 'ohc', 'four', '90', '2bbl', '2.97', '3.23', '9.40', '68', '5500', '31', '38', '6377'], ['1', '118', 'dodge', 'gas', 'turbo', 'two', 'hatchback', 'fwd', 'front', '93.70', '157.30', '63.80', '50.80', '2128', 'ohc', 'four', '98', 'mpfi', '3.03', '3.39', '7.60', '102', '5500', '24', '30', '7957'], ['1', '148', 'dodge', 'gas', 'std', 'four', 'hatchback', 'fwd', 'front', '93.70', '157.30', '63.80', '50.60', '1967', 'ohc', 'four', '90', '2bbl', '2.97', '3.23', '9.40', '68', '5500', '31', '38', '6229'], ['1', '148', 'dodge', 'gas', 'std', 'four', 'sedan', 'fwd', 'front', '93.70', '157.30', '63.80', '50.60', '1989', 'ohc', 'four', '90', '2bbl', '2.97', '3.23', '9.40', '68', '5500', '31', '38', '6692'], ['1', '148', 'dodge', 'gas', 'std', 'four', 'sedan', 'fwd', 'front', '93.70', '157.30', '63.80', '50.60', '1989', 'ohc', 'four', '90', '2bbl', '2.97', '3.23', '9.40', '68', '5500', '31', '38', '7609'], ['1', '148', 'dodge', 'gas', 'turbo', '?', 'sedan', 'fwd', 'front', '93.70', '157.30', '63.80', '50.60', '2191', 'ohc', 'four', '98', 'mpfi', '3.03', '3.39', '7.60', '102', '5500', '24', '30', '8558'], ['-1', '110', 'dodge', 'gas', 'std', 'four', 'wagon', 'fwd', 'front', '103.30', '174.60', '64.60', '59.80', '2535', 'ohc', 'four', '122', '2bbl', '3.34', '3.46', '8.50', '88', '5000', '24', '30', '8921'], ['3', '145', 'dodge', 'gas', 'turbo', 'two', 'hatchback', 'fwd', 'front', '95.90', '173.20', '66.30', '50.20', '2811', 'ohc', 'four', '156', 'mfi', '3.60', '3.90', '7.00', '145', '5000', '19', '24', '12964'], ['2', '137', 'honda', 'gas', 'std', 'two', 'hatchback', 'fwd', 'front', '86.60', '144.60', '63.90', '50.80', '1713', 'ohc', 'four', '92', '1bbl', '2.91', '3.41', '9.60', '58', '4800', '49', '54', '6479'], ['2', '137', 'honda', 'gas', 'std', 'two', 'hatchback', 'fwd', 'front', '86.60', '144.60', '63.90', '50.80', '1819', 'ohc', 'four', '92', '1bbl', '2.91', '3.41', '9.20', '76', '6000', '31', '38', '6855'], ['1', '101', 'honda', 'gas', 'std', 'two', 'hatchback', 'fwd', 'front', '93.70', '150.00', '64.00', '52.60', '1837', 'ohc', 'four', '79', '1bbl', '2.91', '3.07', '10.10', '60', '5500', '38', '42', '5399'], ['1', '101', 'honda', 'gas', 'std', 'two', 'hatchback', 'fwd', 'front', '93.70', '150.00', '64.00', '52.60', '1940', 'ohc', 'four', '92', '1bbl', '2.91', '3.41', '9.20', '76', '6000', '30', '34', '6529'], ['1', '101', 'honda', 'gas', 'std', 'two', 'hatchback', 'fwd', 'front', '93.70', '150.00', '64.00', '52.60', '1956', 'ohc', 'four', '92', '1bbl', '2.91', '3.41', '9.20', '76', '6000', '30', '34', '7129'], ['0', '110', 'honda', 'gas', 'std', 'four', 'sedan', 'fwd', 'front', '96.50', '163.40', '64.00', '54.50', '2010', 'ohc', 'four', '92', '1bbl', '2.91', '3.41', '9.20', '76', '6000', '30', '34', '7295'], ['0', '78', 'honda', 'gas', 'std', 'four', 'wagon', 'fwd', 'front', '96.50', '157.10', '63.90', '58.30', '2024', 'ohc', 'four', '92', '1bbl', '2.92', '3.41', '9.20', '76', '6000', '30', '34', '7295'], ['0', '106', 'honda', 'gas', 'std', 'two', 'hatchback', 'fwd', 'front', '96.50', '167.50', '65.20', '53.30', '2236', 'ohc', 'four', '110', '1bbl', '3.15', '3.58', '9.00', '86', '5800', '27', '33', '7895'], ['0', '106', 'honda', 'gas', 'std', 'two', 'hatchback', 'fwd', 'front', '96.50', '167.50', '65.20', '53.30', '2289', 'ohc', 'four', '110', '1bbl', '3.15', '3.58', '9.00', '86', '5800', '27', '33', '9095'], ['0', '85', 'honda', 'gas', 'std', 'four', 'sedan', 'fwd', 'front', '96.50', '175.40', '65.20', '54.10', '2304', 'ohc', 'four', '110', '1bbl', '3.15', '3.58', '9.00', '86', '5800', '27', '33', '8845'], ['0', '85', 'honda', 'gas', 'std', 'four', 'sedan', 'fwd', 'front', '96.50', '175.40', '62.50', '54.10', '2372', 'ohc', 'four', '110', '1bbl', '3.15', '3.58', '9.00', '86', '5800', '27', '33', '10295'], ['0', '85', 'honda', 'gas', 'std', 'four', 'sedan', 'fwd', 'front', '96.50', '175.40', '65.20', '54.10', '2465', 'ohc', 'four', '110', 'mpfi', '3.15', '3.58', '9.00', '101', '5800', '24', '28', '12945'], ['1', '107', 'honda', 'gas', 'std', 'two', 'sedan', 'fwd', 'front', '96.50', '169.10', '66.00', '51.00', '2293', 'ohc', 'four', '110', '2bbl', '3.15', '3.58', '9.10', '100', '5500', '25', '31', '10345'], ['0', '?', 'isuzu', 'gas', 'std', 'four', 'sedan', 'rwd', 'front', '94.30', '170.70', '61.80', '53.50', '2337', 'ohc', 'four', '111', '2bbl', '3.31', '3.23', '8.50', '78', '4800', '24', '29', '6785'], ['1', '?', 'isuzu', 'gas', 'std', 'two', 'sedan', 'fwd', 'front', '94.50', '155.90', '63.60', '52.00', '1874', 'ohc', 'four', '90', '2bbl', '3.03', '3.11', '9.60', '70', '5400', '38', '43', '?'], ['0', '?', 'isuzu', 'gas', 'std', 'four', 'sedan', 'fwd', 'front', '94.50', '155.90', '63.60', '52.00', '1909', 'ohc', 'four', '90', '2bbl', '3.03', '3.11', '9.60', '70', '5400', '38', '43', '?'], ['2', '?', 'isuzu', 'gas', 'std', 'two', 'hatchback', 'rwd', 'front', '96.00', '172.60', '65.20', '51.40', '2734', 'ohc', 'four', '119', 'spfi', '3.43', '3.23', '9.20', '90', '5000', '24', '29', '11048'], ['0', '145', 'jaguar', 'gas', 'std', 'four', 'sedan', 'rwd', 'front', '113.00', '199.60', '69.60', '52.80', '4066', 'dohc', 'six', '258', 'mpfi', '3.63', '4.17', '8.10', '176', '4750', '15', '19', '32250'], ['0', '?', 'jaguar', 'gas', 'std', 'four', 'sedan', 'rwd', 'front', '113.00', '199.60', '69.60', '52.80', '4066', 'dohc', 'six', '258', 'mpfi', '3.63', '4.17', '8.10', '176', '4750', '15', '19', '35550'], ['0', '?', 'jaguar', 'gas', 'std', 'two', 'sedan', 'rwd', 'front', '102.00', '191.70', '70.60', '47.80', '3950', 'ohcv', 'twelve', '326', 'mpfi', '3.54', '2.76', '11.50', '262', '5000', '13', '17', '36000'], ['1', '104', 'mazda', 'gas', 'std', 'two', 'hatchback', 'fwd', 'front', '93.10', '159.10', '64.20', '54.10', '1890', 'ohc', 'four', '91', '2bbl', '3.03', '3.15', '9.00', '68', '5000', '30', '31', '5195'], ['1', '104', 'mazda', 'gas', 'std', 'two', 'hatchback', 'fwd', 'front', '93.10', '159.10', '64.20', '54.10', '1900', 'ohc', 'four', '91', '2bbl', '3.03', '3.15', '9.00', '68', '5000', '31', '38', '6095'], ['1', '104', 'mazda', 'gas', 'std', 'two', 'hatchback', 'fwd', 'front', '93.10', '159.10', '64.20', '54.10', '1905', 'ohc', 'four', '91', '2bbl', '3.03', '3.15', '9.00', '68', '5000', '31', '38', '6795'], ['1', '113', 'mazda', 'gas', 'std', 'four', 'sedan', 'fwd', 'front', '93.10', '166.80', '64.20', '54.10', '1945', 'ohc', 'four', '91', '2bbl', '3.03', '3.15', '9.00', '68', '5000', '31', '38', '6695'], ['1', '113', 'mazda', 'gas', 'std', 'four', 'sedan', 'fwd', 'front', '93.10', '166.80', '64.20', '54.10', '1950', 'ohc', 'four', '91', '2bbl', '3.08', '3.15', '9.00', '68', '5000', '31', '38', '7395'], ['3', '150', 'mazda', 'gas', 'std', 'two', 'hatchback', 'rwd', 'front', '95.30', '169.00', '65.70', '49.60', '2380', 'rotor', 'two', '70', '4bbl', '?', '?', '9.40', '101', '6000', '17', '23', '10945'], ['3', '150', 'mazda', 'gas', 'std', 'two', 'hatchback', 'rwd', 'front', '95.30', '169.00', '65.70', '49.60', '2380', 'rotor', 'two', '70', '4bbl', '?', '?', '9.40', '101', '6000', '17', '23', '11845'], ['3', '150', 'mazda', 'gas', 'std', 'two', 'hatchback', 'rwd', 'front', '95.30', '169.00', '65.70', '49.60', '2385', 'rotor', 'two', '70', '4bbl', '?', '?', '9.40', '101', '6000', '17', '23', '13645'], ['3', '150', 'mazda', 'gas', 'std', 'two', 'hatchback', 'rwd', 'front', '95.30', '169.00', '65.70', '49.60', '2500', 'rotor', 'two', '80', 'mpfi', '?', '?', '9.40', '135', '6000', '16', '23', '15645'], ['1', '129', 'mazda', 'gas', 'std', 'two', 'hatchback', 'fwd', 'front', '98.80', '177.80', '66.50', '53.70', '2385', 'ohc', 'four', '122', '2bbl', '3.39', '3.39', '8.60', '84', '4800', '26', '32', '8845'], ['0', '115', 'mazda', 'gas', 'std', 'four', 'sedan', 'fwd', 'front', '98.80', '177.80', '66.50', '55.50', '2410', 'ohc', 'four', '122', '2bbl', '3.39', '3.39', '8.60', '84', '4800', '26', '32', '8495'], ['1', '129', 'mazda', 'gas', 'std', 'two', 'hatchback', 'fwd', 'front', '98.80', '177.80', '66.50', '53.70', '2385', 'ohc', 'four', '122', '2bbl', '3.39', '3.39', '8.60', '84', '4800', '26', '32', '10595'], ['0', '115', 'mazda', 'gas', 'std', 'four', 'sedan', 'fwd', 'front', '98.80', '177.80', '66.50', '55.50', '2410', 'ohc', 'four', '122', '2bbl', '3.39', '3.39', '8.60', '84', '4800', '26', '32', '10245'], ['0', '?', 'mazda', 'diesel', 'std', '?', 'sedan', 'fwd', 'front', '98.80', '177.80', '66.50', '55.50', '2443', 'ohc', 'four', '122', 'idi', '3.39', '3.39', '22.70', '64', '4650', '36', '42', '10795'], ['0', '115', 'mazda', 'gas', 'std', 'four', 'hatchback', 'fwd', 'front', '98.80', '177.80', '66.50', '55.50', '2425', 'ohc', 'four', '122', '2bbl', '3.39', '3.39', '8.60', '84', '4800', '26', '32', '11245'], ['0', '118', 'mazda', 'gas', 'std', 'four', 'sedan', 'rwd', 'front', '104.90', '175.00', '66.10', '54.40', '2670', 'ohc', 'four', '140', 'mpfi', '3.76', '3.16', '8.00', '120', '5000', '19', '27', '18280'], ['0', '?', 'mazda', 'diesel', 'std', 'four', 'sedan', 'rwd', 'front', '104.90', '175.00', '66.10', '54.40', '2700', 'ohc', 'four', '134', 'idi', '3.43', '3.64', '22.00', '72', '4200', '31', '39', '18344'], ['-1', '93', 'mercedes-benz', 'diesel', 'turbo', 'four', 'sedan', 'rwd', 'front', '110.00', '190.90', '70.30', '56.50', '3515', 'ohc', 'five', '183', 'idi', '3.58', '3.64', '21.50', '123', '4350', '22', '25', '25552'], ['-1', '93', 'mercedes-benz', 'diesel', 'turbo', 'four', 'wagon', 'rwd', 'front', '110.00', '190.90', '70.30', '58.70', '3750', 'ohc', 'five', '183', 'idi', '3.58', '3.64', '21.50', '123', '4350', '22', '25', '28248'], ['0', '93', 'mercedes-benz', 'diesel', 'turbo', 'two', 'hardtop', 'rwd', 'front', '106.70', '187.50', '70.30', '54.90', '3495', 'ohc', 'five', '183', 'idi', '3.58', '3.64', '21.50', '123', '4350', '22', '25', '28176'], ['-1', '93', 'mercedes-benz', 'diesel', 'turbo', 'four', 'sedan', 'rwd', 'front', '115.60', '202.60', '71.70', '56.30', '3770', 'ohc', 'five', '183', 'idi', '3.58', '3.64', '21.50', '123', '4350', '22', '25', '31600'], ['-1', '?', 'mercedes-benz', 'gas', 'std', 'four', 'sedan', 'rwd', 'front', '115.60', '202.60', '71.70', '56.50', '3740', 'ohcv', 'eight', '234', 'mpfi', '3.46', '3.10', '8.30', '155', '4750', '16', '18', '34184'], ['3', '142', 'mercedes-benz', 'gas', 'std', 'two', 'convertible', 'rwd', 'front', '96.60', '180.30', '70.50', '50.80', '3685', 'ohcv', 'eight', '234', 'mpfi', '3.46', '3.10', '8.30', '155', '4750', '16', '18', '35056'], ['0', '?', 'mercedes-benz', 'gas', 'std', 'four', 'sedan', 'rwd', 'front', '120.90', '208.10', '71.70', '56.70', '3900', 'ohcv', 'eight', '308', 'mpfi', '3.80', '3.35', '8.00', '184', '4500', '14', '16', '40960'], ['1', '?', 'mercedes-benz', 'gas', 'std', 'two', 'hardtop', 'rwd', 'front', '112.00', '199.20', '72.00', '55.40', '3715', 'ohcv', 'eight', '304', 'mpfi', '3.80', '3.35', '8.00', '184', '4500', '14', '16', '45400'], ['1', '?', 'mercury', 'gas', 'turbo', 'two', 'hatchback', 'rwd', 'front', '102.70', '178.40', '68.00', '54.80', '2910', 'ohc', 'four', '140', 'mpfi', '3.78', '3.12', '8.00', '175', '5000', '19', '24', '16503'], ['2', '161', 'mitsubishi', 'gas', 'std', 'two', 'hatchback', 'fwd', 'front', '93.70', '157.30', '64.40', '50.80', '1918', 'ohc', 'four', '92', '2bbl', '2.97', '3.23', '9.40', '68', '5500', '37', '41', '5389'], ['2', '161', 'mitsubishi', 'gas', 'std', 'two', 'hatchback', 'fwd', 'front', '93.70', '157.30', '64.40', '50.80', '1944', 'ohc', 'four', '92', '2bbl', '2.97', '3.23', '9.40', '68', '5500', '31', '38', '6189'], ['2', '161', 'mitsubishi', 'gas', 'std', 'two', 'hatchback', 'fwd', 'front', '93.70', '157.30', '64.40', '50.80', '2004', 'ohc', 'four', '92', '2bbl', '2.97', '3.23', '9.40', '68', '5500', '31', '38', '6669'], ['1', '161', 'mitsubishi', 'gas', 'turbo', 'two', 'hatchback', 'fwd', 'front', '93', '157.30', '63.80', '50.80', '2145', 'ohc', 'four', '98', 'spdi', '3.03', '3.39', '7.60', '102', '5500', '24', '30', '7689'], ['3', '153', 'mitsubishi', 'gas', 'turbo', 'two', 'hatchback', 'fwd', 'front', '96.30', '173.00', '65.40', '49.40', '2370', 'ohc', 'four', '110', 'spdi', '3.17', '3.46', '7.50', '116', '5500', '23', '30', '9959'], ['3', '153', 'mitsubishi', 'gas', 'std', 'two', 'hatchback', 'fwd', 'front', '96.30', '173.00', '65.40', '49.40', '2328', 'ohc', 'four', '122', '2bbl', '3.35', '3.46', '8.50', '88', '5000', '25', '32', '8499'], ['3', '?', 'mitsubishi', 'gas', 'turbo', 'two', 'hatchback', 'fwd', 'front', '95.90', '173.20', '66.30', '50.20', '2833', 'ohc', 'four', '156', 'spdi', '3.58', '3.86', '7.00', '145', '5000', '19', '24', '12629'], ['3', '?', 'mitsubishi', 'gas', 'turbo', 'two', 'hatchback', 'fwd', 'front', '95.90', '173.20', '66.30', '50.20', '2921', 'ohc', 'four', '156', 'spdi', '3.59', '3.86', '7.00', '145', '5000', '19', '24', '14869'], ['3', '?', 'mitsubishi', 'gas', 'turbo', 'two', 'hatchback', 'fwd', 'front', '95.90', '173.20', '66.30', '50.20', '2926', 'ohc', 'four', '156', 'spdi', '3.59', '3.86', '7.00', '145', '5000', '19', '24', '14489'], ['1', '125', 'mitsubishi', 'gas', 'std', 'four', 'sedan', 'fwd', 'front', '96.30', '172.40', '65.40', '51.60', '2365', 'ohc', 'four', '122', '2bbl', '3.35', '3.46', '8.50', '88', '5000', '25', '32', '6989'], ['1', '125', 'mitsubishi', 'gas', 'std', 'four', 'sedan', 'fwd', 'front', '96.30', '172.40', '65.40', '51.60', '2405', 'ohc', 'four', '122', '2bbl', '3.35', '3.46', '8.50', '88', '5000', '25', '32', '8189'], ['1', '125', 'mitsubishi', 'gas', 'turbo', 'four', 'sedan', 'fwd', 'front', '96.30', '172.40', '65.40', '51.60', '2403', 'ohc', 'four', '110', 'spdi', '3.17', '3.46', '7.50', '116', '5500', '23', '30', '9279'], ['-1', '137', 'mitsubishi', 'gas', 'std', 'four', 'sedan', 'fwd', 'front', '96.30', '172.40', '65.40', '51.60', '2403', 'ohc', 'four', '110', 'spdi', '3.17', '3.46', '7.50', '116', '5500', '23', '30', '9279'], ['1', '128', 'nissan', 'gas', 'std', 'two', 'sedan', 'fwd', 'front', '94.50', '165.30', '63.80', '54.50', '1889', 'ohc', 'four', '97', '2bbl', '3.15', '3.29', '9.40', '69', '5200', '31', '37', '5499'], ['1', '128', 'nissan', 'diesel', 'std', 'two', 'sedan', 'fwd', 'front', '94.50', '165.30', '63.80', '54.50', '2017', 'ohc', 'four', '103', 'idi', '2.99', '3.47', '21.90', '55', '4800', '45', '50', '7099'], ['1', '128', 'nissan', 'gas', 'std', 'two', 'sedan', 'fwd', 'front', '94.50', '165.30', '63.80', '54.50', '1918', 'ohc', 'four', '97', '2bbl', '3.15', '3.29', '9.40', '69', '5200', '31', '37', '6649'], ['1', '122', 'nissan', 'gas', 'std', 'four', 'sedan', 'fwd', 'front', '94.50', '165.30', '63.80', '54.50', '1938', 'ohc', 'four', '97', '2bbl', '3.15', '3.29', '9.40', '69', '5200', '31', '37', '6849'], ['1', '103', 'nissan', 'gas', 'std', 'four', 'wagon', 'fwd', 'front', '94.50', '170.20', '63.80', '53.50', '2024', 'ohc', 'four', '97', '2bbl', '3.15', '3.29', '9.40', '69', '5200', '31', '37', '7349'], ['1', '128', 'nissan', 'gas', 'std', 'two', 'sedan', 'fwd', 'front', '94.50', '165.30', '63.80', '54.50', '1951', 'ohc', 'four', '97', '2bbl', '3.15', '3.29', '9.40', '69', '5200', '31', '37', '7299'], ['1', '128', 'nissan', 'gas', 'std', 'two', 'hatchback', 'fwd', 'front', '94.50', '165.60', '63.80', '53.30', '2028', 'ohc', 'four', '97', '2bbl', '3.15', '3.29', '9.40', '69', '5200', '31', '37', '7799'], ['1', '122', 'nissan', 'gas', 'std', 'four', 'sedan', 'fwd', 'front', '94.50', '165.30', '63.80', '54.50', '1971', 'ohc', 'four', '97', '2bbl', '3.15', '3.29', '9.40', '69', '5200', '31', '37

,symboling,normalized_losses,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.60,...,130,mpfi,3.47,2.68,9.00,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.60,...,130,mpfi,3.47,2.68,9.00,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.50,...,152,mpfi,2.68,3.47,9.00,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.80,...,109,mpfi,3.19,3.40,10.00,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.40,...,136,mpfi,3.19,3.40,8.00,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.10,...,141,mpfi,3.78,3.15,9.50,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.10,...,141,mpfi,3.78,3.15,8.70,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.10,...,173,mpfi,3.58,2.87,8.80,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.10,...,145,idi,3.01,3.40,23.00,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.10,...,141,mpfi,3.78,3.15,9.50,114,5400,19,25,22625

In [93]:
df_weather = pd.read_csv("Data/weather_data.csv", skiprows=1)
df_weather

                                      asdsadfs
day       temperature   windspeed        event
1/1/2017  32            6                 Rain
1/4/2017  not available 9                Sunny
1/5/2017  -1            not measured      Snow
1/6/2017  not available 7             no event
1/7/2017  32            not measured      Rain
1/8/2017  not available not measured     Sunny
1/9/2017  not available not measured  no event
1/10/2017 34            8               Cloudy
1/11/2017 -4            -1                Snow
1/12/2017 26            12               Sunny
1/13/2017 12            12               Rainy
1/11/2017 -1            12                Snow
1/14/2017 40            -1               Sunny

In [46]:
df_weather = pd.read_csv("Data/weather_data.csv", header=2)
df_weather

          day    temperature     windspeed     event
0    1/1/2017             32             6      Rain
1    1/4/2017  not available             9     Sunny
2    1/5/2017             -1  not measured      Snow
3    1/6/2017  not available             7  no event
4    1/7/2017             32  not measured      Rain
5    1/8/2017  not available  not measured     Sunny
6    1/9/2017  not available  not measured  no event
7   1/10/2017             34             8    Cloudy
8   1/11/2017             -4            -1      Snow
9   1/12/2017             26            12     Sunny
10  1/13/2017             12            12     Rainy
11  1/11/2017             -1            12      Snow
12  1/14/2017             40            -1     Sunny